#ifndef SOUNDLIST_H
#define SOUNDLIST_H

enum SOUNDS
{
	soundEffectPusleRifleShot,
	soundEffectEnergyBoost,
	soundEffectBulletPlayerHit,
	soundEffectGrenadeLauncher,
	soundEffectShotGun,
	soundEffectDiscGun,
	soundEffectLinkGun,
	soundEffectMelee,
	firstBlood,
	soundFootSteps,
	soundStepsManipulator,
	soundEffectTrapperReload,
	soundEffectShield,
	soundEffectDiscBounce,
	soundEffectBruteSteps,
	soundEffectShankerSteps,
	soundEffectClusterGrenade,
	soundEffectVacuumGrenade,
	soundAids,
	power,
	soundEffectGrenadeBounce,
	soundEffectHackingDart,
	soundEffectLightSpeed,
	soundEffectTrapperJump,
	soundEffectTrapperLand,
	soundEffectTrapperMultiJump,
	soundEffectLightWall,
	soundEffectYouDied,
	soundEffectHunterJump,
	soundEffectOcean,
	soundEffectFlies,
	soundEffectFrogs,
	soundEffectNeonSign,
	soundEffectClusterlingExplosion,
	soundEffectCrows,
	BreakingOutBass,
	soundEffectBruteLand,
	soundEffectBruteJump,
	soundEffectGrenadeLauncherBounce,
	soundEffectStalkerReload,
	YouWin,
	YouLose,
	SoundForOvertime,
	hackedSound,
	announcer5Seconds,
	announcer15Seconds,
	announcer5Tokens,
	announcerCommence,
	announcerCaptureZoneBreached,
	announcerKillingSpree,
	announcerImpressive,
	announcerRound1,
	announcerRound2,
	announcerRound3,
	announcerYouLose,
	announcerYouWin,
	announcerCleanup,
	soundEffectCaptureScored,
	soundEffectBruteDash,
	soundEffectThermiteGrenade,
	soundEffectPunisherReload,
	soundEffectDestroyerStart,
	soundEffectDestroyerStop,
	soundEffectDestroyerSteps,
	soundEffectHP,
	soundEffectRespawn,
	soundEffectBulletPlayerHitSelf,
	soundEffectBruteStepsStereo,
	soundEffectEnergyBoostStereo,
	soundEffectGrenadeLauncherStereo,
	soundEffectHunterJumpStereo,
	soundEffectLightSpeedStereo,
	soundEffectLightWallStereo,
	soundEffectMeleeStereo,
	soundEffectPulseRifleShotStereo,
	soundEffectShankerStepsStereo,
	soundEffectShotGunStereo,
	soundEffectTrapperJumpStereo,
	soundEffectTrapperLandStereo,
	soundEffectTrapperMultiJumpStereo,
	soundFootStepsStereo,
	soundEffectDiscGunStereo,
	soundEffectBruteDashStereo,
	soundEffectLinkGunStereo,
	soundStepsManipulatorStereo,

	nrOfSounds //leave last
};

enum MUSIC
{
	mainMenu,
	cantinaSong,

	nrOfMusic
};

#endif